name: Update S3

on:
  push:
    branches:
      - master

jobs:
  updater:
    name: S3 Updater Job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update
      uses: ./.github/updater/
